#-------------------------------
# General Site Settings

title: SOSConf
logo: "assets/images/sosconf_logo_white.png"
author: 
description: Students Open Source Conference
email: 2021.zh@sosconf.org
phone: 
address: 1088 Xueyuan Avenue, Shenzhen 518055, P.R. China
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com) & Modified by [Wyatt Feng](https://github.com/wyatt-feng)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Sponsors, link: '/sponsors'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

#disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Students Open Source Conference <br>@ SUSTech

social:
- {icon: "ti-facebook", link: "https://fb.com/sosconf"}
- {icon: "ti-instagram", link: "https://twitter.com/sosconf"}
# - {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "https://twitter.com/sosconf"}
- {icon: "ti-weibo", link: "https://weibo.com/sosconf"}
- {icon: "assets/images/icons/qq.png", link: "https://jq.qq.com/?_wv=1027&k=DrhmWRAz"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  SOSConf is the first global open-source technology summit organized by students for non-profit community. Based on the concept of open source, the summit encourages students to enjoy open source, understand open source, participate in open source, contribute to open source, and get practice and fun from open source. 

blurb-btn-link: '/about'
blurb-btn-name: more details


# About Page

# # Work Process Section
# work-process:
#   - title : "Research and Plan"
#     icon : "assets/images/icons/plan.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Design and Develop"
#     icon : "assets/images/icons/design.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Deliver"
#     icon : "assets/images/icons/print.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Zhenjiang MAO"
    image : "assets/images/team/mzj.png"
    designation : "Chairman & Fundraiser"

  - title : "Minghui NIU"
    image : "assets/images/team/default.jpg"
    designation : "Conference Coordinator"
  
  - title : "Yuntian WANG"
    image : "assets/images/team/default.jpg"
    designation : "Publicity"
  
  - title : "Zhongze YING"
    image : "assets/images/team/default.jpg"
    designation : "Media Coordinator"
  
  - title : "Wyatt Feng"
    image : "assets/images/team/fdz.jpg"
    designation : "Webmaster"


#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Web Design, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

# experience-title: Experience
# experience:
# - {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
# - {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
# - {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

# education-title: Education
# education:
# - {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
# - {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: Information
services:
- {
    name: Live Stream,
    icon: ti-desktop,
    description: Coming Soon,
    active: 
  }
- {
    name: Email Contact,
    icon: ti-email,
    description: 2021.zh@sosconf.org,
    active: true
  }
- {
    name: QQ Group,
    icon: ti-comments,
    description: 337055895,
    active: true
  }



#-------------------------------
# Sponsors (Section and Page)

# Sponsors Home Section
sponsors-home-items:
  - image : "assets/images/sponsors/comingsoon.png"
#    url: "#"
    

# Sponsors Page
sponsors-label:
- {
    title : "Platinum Sponsor",
    type : "platinum"
  }
- {
    title : "Gold Sponsor",
    type : "gold"
  }
- {
    title : "Silver Sponsor",
    type : "silver"
  }

# sponsors-items:
#   - image : "assets/images/sponsors/item-1.png"
#     url: "#"
#     sponsors-type:
#      - type: "design"
#      - type: "illustration"
      


#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

# contact-title: Contact Info
# contact-email: 2021zh.sosconf.org
